# Use postgres/example user/password credentials
version: '3.1'

services:
  sqs:
    image: softwaremill/elasticmq
    restart: always
    ports:
      - '9324:9324'
  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - '9000:9000'
      - '9092:9092'
